
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int por = 4;
  public static final int decimal = 7;
  public static final int entero = 6;
  public static final int error = 1;
  public static final int mas = 2;
  public static final int menos = 3;
  public static final int EOF = 0;
  public static final int dividido = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "por",
  "dividido",
  "entero",
  "decimal"
  };
}

